In [14]:
pip install shutil

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement shutil (from versions: none)
ERROR: No matching distribution found for shutil

In [99]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
import csv
import shutil
import pandas as pd

import warnings
import os

In [29]:
warnings.filterwarnings("ignore")

In [84]:
airlines = ["Alaska Airlines Inc. (AS)","American Airlines Inc. (AA)","Delta Airlines Inc. (DL)","Frontier Airlines Inc. (F9)","JetBlue Airways (B6)","Southwest Airlines Co. (WN)","Spirit Airlines (NK)","United Airlines Inc. (UA)"]

In [74]:
driver = webdriver.Chrome(executable_path= r'chromedriver.exe')
url = 'https://www.transtats.bts.gov/ontime/departures.aspx'
driver.get(url)

In [77]:
driver.find_element("id","chkStatistics_4").click()
driver.find_element("id","cboAirport").click()
#filter airport ot houston 
driver.find_element("xpath","//*[contains(text(),'George Bush Intercontinental/Houston (IAH)')]").click()
#click allmonths, all days and 2022
   #click all dates and all years 
driver.find_element("id", "chkAllMonths").click()
driver.find_element("id", "chkAllDays").click()
driver.find_element("id", "chkYears_35").click()

In [79]:
#TEST
# driver.find_element("id","cboAirline").click()
# driver.find_element("xpath","//*[contains(text(),'Frontier Airlines Inc. (F9)')]").click()
# driver.find_element("id", "btnSubmit").click()
# time.sleep(10)
# driver.find_element("id", "DL_CSV").click()
# time.sleep(20)
# download_dir = r"C:\Users\memel\Downloads"
# file_name = "Detailed_Statistics_Departures.csv"
# file_path = os.path.join(download_dir, file_name)
# destination_dir = r"C:\Users\memel\OneDrive\Desktop\Project3\CSV"
# os.makedirs(destination_dir, exist_ok=True)

#     # Rename and move the downloaded file to the destination directory
# destination_file = os.path.join(destination_dir, "alaska.csv")
# shutil.move(file_path, destination_file)
# time.sleep(5)
""

''

In [85]:
csv_names = []
for airline in airlines:
    try:

#filter airport ot houston 
    #click airport dropdown
        time.sleep(10)
        driver.find_element("id","cboAirline").click()
        #clickdropdown an then find airline name 
        driver.find_element("xpath", "//*[contains(text(),'" + airline + "')]").click()

        #click submit button
        driver.find_element("id", "btnSubmit").click()
        #wait for page to load
        time.sleep(5)
        
        # #export the csv
        driver.find_element("id", "DL_CSV").click()
        #wait for it to download 
        time.sleep(20)
        #CHANGE FOR YOUR DOWNLOAD PATH 
        download_dir = r"C:\..\..\Downloads"
        file_name = "Detailed_Statistics_Departures.csv"
        file_path = os.path.join(download_dir, file_name)
    
        # Set the destination directory CHANGE TO YOUR FILE PATH 
        destination_dir = r"C:\Users\memel\OneDrive\Desktop\Project3\CSV"
        os.makedirs(destination_dir, exist_ok=True)

        # Rename and move the downloaded file to the destination directory
        destination_file = os.path.join(destination_dir, airline + ".csv")
        shutil.move(file_path, destination_file)
        csv_names.append(f"{airline}.csv")
        time.sleep(5)
    except Exception as e:
        print(f"Error occured for airline {airline} skipping.. Error message {str(e)}")

In [86]:
print(csv_names)

['Alaska Airlines Inc. (AS).csv', 'American Airlines Inc. (AA).csv', 'Delta Airlines Inc. (DL).csv', 'Frontier Airlines Inc. (F9).csv', 'JetBlue Airways (B6).csv', 'Southwest Airlines Co. (WN).csv', 'Spirit Airlines (NK).csv', 'United Airlines Inc. (UA).csv']

In [117]:
df = 0
for csv in csv_names:
    path = os.path.join(r"CSV",csv)
    
    # results=pd.read_csv(path)
    # if df == 0:
    #     df[csv]=pd.DataFrame(results)
    # else:
    #     combined_df = pd.

In [116]:
path = os.path.join(r"CSV","Alaska Airlines Inc. (AS).csv")
with open(path,encoding='utf') as csvfile:
    csvreader = csv.reader(csvfile,delimiter=',')
    df = pd.DataFrame(csvreader)
    
df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,Detailed Statistics Departures,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,Origin Airport: Houston,TX: George Bush Intercontinental/Houston (IAH),None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,Airline: Alaska Airlines Inc. (AS),None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,Month(s): January,February,March,April,May,June,July,August,September,October,...,None,None,None,None,None,None,None,None,None,None
4,Day(s): 1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30 and 31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,AS,12/30/2022,0263,N434AS,SEA,0,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
698,AS,12/30/2022,0698,N440AS,SEA,51,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
699,AS,12/31/2022,0263,N949AK,SEA,-6,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
700,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
701,SOURCE: Bureau of Transportation Statistics,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
# driver.implicitly_wait(10)

In [ ]:
# shutil.copy(os.path.join(),dst_file)
# os.rename.name[i]